version: '3'

volumes:
  postgres-data:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:

services:
  docker:
    container_name: docker
    image: docker:dind
    privileged: true
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - $HOME:/home
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    # image: jenkins/jenkins:lts
    container_name: jenkins
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - $HOME:/home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_VERIFY=1

  postgres:
    container_name: postgres
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - postgres-data:/var/lib/postgresql/data

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres
