version: '2'

networks:
  jenkins:

services:

  jenkins:
    # image: jenkins/jenkins:lts
    image: jenkinsci/blueocean
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - $HOME/docker/jenkins-docker-certs:/certs/client:ro
      - $HOME/docker/jenkins_home:/var/jenkins_home
      - $HOME:/home
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_CERTDIR=/certs 
      - DOCKER_TLS_VERIFY=1

  dockerindocker:
    image: docker:dind
    privileged: true
    networks:
      - jenkins
    volumes:
      - $HOME/docker/jenkins-docker-certs:/certs/client
      - $HOME/docker/jenkins_home:/var/jenkins_home
      - $HOME:/home
    environment: 
      - DOCKER_TLS_CERTDIR=/certs

  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - $HOME/docker/postgres-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres
